### PR TITLE
Release 4.4.1

### PR DESCRIPTION
**Pull request by ekohl**
I have marked this as a patch release but I'm considering a minor version.

### CODE REVIEW

**Comment by evgeni** [comment]
Would you explain why you would consider a minor bump?
It's fixing a bug, no new (Puppet) dependencies are introduced and no behavior change happens, so imho patch is fine.

**Comment by ekohl** [comment]
That was also my reasoning but wasn't sure about potential impact. Of course your code is perfect and would never contain bugs, but I sometimes bump to a minor when a bugfix is larger. That said, I'm fine with considering this a patch release.

**Comment by evgeni** [comment]
never said my code is even good ;-) (but it seems to work XD)

**Comment by ehelms** [comment]
@ekohl Letting you merge this so you can release it at the same time

**Pull request merged**
